[package]
name = "tfsys"
version = "0.1.0"
authors = ["Nicolas Bigaouette <nbigaouette@gmail.com>"]

build = "build.rs"
links = "tensorflow"

[dependencies]

[build-dependencies]
curl = "0.4"
flate2 = "0.2"
tar = "0.4"
