[package]
name = "tfsys"
version = "0.1.0"
authors = ["Nicolas Bigaouette <nbigaouette@gmail.com>"]

build = "build.rs"
links = "tensorflow"

[dependencies]
libc = "0.2"

[build-dependencies]
curl = "0.4"
flate2 = "0.2"
pkg-config = "0.3"
semver = "0.5"
tar = "0.4"

[features]
tensorflow_gpu = []
